.gitignore
README.md
go.mod
go.sum
src/bucketblocker/main.go

An early implementation of the script. It takes in
- bucket name (required)
- AWS profile (optional)
- AWS region (optional)
and attempts to block all public access for the named bucket
Eventually, I would like this to evolve into a project that performs this operation on all buckets in an account, apart from named exceptions, but this is a good starting point.
I wanted this project to be available as a small binary that developers could download directly from GitHub. Also, I wanted to experiment with Go a bit more, and this small, temporary, standalone project seemed like a good time to do it.
Create a bucket in S3, and run this script against it.
This project exists because we are required to comply with AWS Foundational Security Best Practices (FSBP) control S3.8, which requires that …

Take one bucket, block its public access

---

README.md
main.go
utils/awsutils.go
utils/utils.go

- Allows user to specify the maximum number of buckets they would like to block, up to 100, so they can trial the tool
- Ask the user to confirm that they would like to move ahead with the changes before blocking public access
- Improved the log messages a little
Follow the instructions in the README, experiment with the `-max` and `-dry-run` flags. Note that the format for the CLI has switched from `-flag value` to `-flag=value` (with an `=` rather than a space) as the spaced syntax is not compatible with boolean arguments. Please be careful not to hit `y` on the confirmation dialogue, as you will then start making changes to the account.
Teams feel more confident testing out the tool on a small number of buckets. Improved user experience.

Add confirmation dialogue. Allow user to customise bucket count.

---

.github/workflows/ci.yaml
.gitignore
.releaserc.yaml
script/build.sh

Adds the steps to the workflow that build the binary and release it to Github.
See the steps run successfully below. Release should occur when this PR is merged. We can be reasonably confident that the release step now works from [this successful run](https://github.com/guardian/bucket-blocker/actions/runs/9585022551/job/26430014765)

ci: add build and release steps

---

.github/workflows/ci.yaml
.gitignore
script/build.sh

- Makes a few changes to the build script, specifically adding a bit of boilerplate so you don't have to be in the root folder to run the script (hence the pushd and popd commands). This is fairly standard.
- More importantly, packages the release builds into tarballs instead of raw binaries.
- Prints SHA256 digests to stdout and adds them to the build summary, if run in Github Actions.
This tool will be distributed via homebrew, which requires tarballs for distribution, as well as SHA digests for formulae.
1. You'll still be able to run the script locally.
```
$ ./script/build.sh
=== Creating release for Darwin arm64 ===
The following is the SHA256 sum for the 'bucketblocker_darwin-arm64.tar.gz' bundle:
65da2929b1ef06e723fb5f936c8c66a309b66d3cf6f120c2b22d12d0b58aaf00
=== Creating release …
```

Package binaries into tarballs

---

.releaserc.json

Hopefully the last PR here!
The action was not uploading any assets to the release, so I checked the logs, and lo and behold:
```
[2:27:12 PM] [semantic-release] [@semantic-release/github] › ✘  The asset bin/bucketblocker-darwin-arm64 cannot be read, and will be ignored.
[2:27:12 PM] [semantic-release] [@semantic-release/github] › ✘  The asset bin/bucketblocker-darwin-amd64 cannot be read, and will be ignored.
```
Turns out I'd forgotten to update the asset configuration file.
For now, I have manually added the tarballs to the latest release, but this fix should do this automatically going foward.

Point to correct assets

---

.github/workflows/ci.yaml
.gitignore
.releaserc.json
README.md
go.mod
main.go
script/build.sh

Makes the spelling of bucket-blocker consistent across the repo.
CI passes, binaries use the correct version (with a -)

make spelling of bucket-blocker consistent

---

.github/workflows/ci.yaml
script/build.sh
script/dash-lint.sh

Enforces the spelling of bucket-blocker, for consistency. Previously this has cause issues such  as the brew formula being called bucket-blocker, but the program being executed using bucketblocker, which is a very odd user experience. Potentially this could be set up as a pre-commit hook, but that requires the user to (at a minimum) follow some setup instructions, which is not guaranteed to happen. A hook could also be set up using the same script as a later date.
The `-i` flag in grep indicates that matches should disregard case, so we will catch other varieties such as `BucketBlocker`, `bucketBlocker`, `BUCKETBLOCKER`, etc.
CI should fail when it runs on a bad commit (see the action run on the first commit)
This doesn't happen again

ci: enforce the use of a dash between bucket and blocker

---

README.md

bucket-blocker is now available on brew. Updating the README/running instructions to reflect that
Follow the README instructions and verify that they work
Better user experience
Keeping brew updated is a manual process. Highly likely that the repo and brew will end up out of sync. We should find a way to keep them updated in the future.

docs: update readme to reflect release to brew.

---

utils/awsutils.go
utils/awsutils_test.go
utils/utils.go

We are not finding all the buckets that exist in stacks. To fix/debug this, the following has been implemented:
- Paginates `ListStacks` and `ListStackResources`, so that we can gather a more complete list of buckets that should not have their access blocked
- Created `FindBucketsInStack`, a pure function that can be tested to verify its behaviour.
Separately, there's a small QOL to the parsing of the -exclusions argument that makes life (aka reading the logs) a little easier. If we are passed an empty string, it won't even attempt to `SplitAndTrim`, and will instead, immediately return an empty slice.
Use local running instructions to verify behaviour.
Less stack drift when the tool is applied.

fix: Find more buckets

---

.github/actions/build/action.yaml
.github/workflows/ci.yaml
.releaserc.json
script/build.sh

- Generalise bucket-blocker's build script so that it also works for ingress-inquisition
- Create a reusable workflow for building and uploading artifacts, use it to build both tools
- Modify the release steps to reflect the new ingress-inquisition artifacts
To test, I allowed releases to be run from non-main branches, and ran the full action. You can see the output [here](https://github.com/guardian/fsbp-tools/actions/runs/10485646173).
This generated [v2.1.0](https://github.com/guardian/fsbp-tools/releases/tag/v2.1.0), which i will remove the pre-release tag from on merge.

Build and release new ingress-inquisition artifacts

---

.github/workflows/ci.yaml

Having a step called `Release` could imply to new contributors/maintainers who only skimmed the readme that running this step is all that is required to create a new release on brew, which is not the case. Now we are being clear about exactly what this step is doing
Less dev confusion

ci: clarify release step

---

ingress-inquisition/main.go
ingress-inquisition/utils/awsutils.go

Previously, ingress-inquisition would always prompt for user permission to delete security group rules, even if there were none to delete. This is confusing behaviour. Now, if there are no rules to delete, the program simply prints `No unused security groups found` and exits.
I also moved some logs around.
This PR is much easier to review in [unified view, with whitespace off](https://github.com/guardian/fsbp-tools/pull/37/files?diff=unified&w=1), as most of the changes are moving things in and out of if/else blocks
Run the program against the Deploy Tools account, which has no instances of this rule being broken
Less confusing user experience

fix: Skip user confirmation and execution if there are no security group rules to delete

---

.github/workflows/ci.yaml
.releaserc.json

Co-authored-by: @tjsilver 
Updates the release config to point only to fsbp-fix tools
We verified this by creating a pre release with the correct artifacts attached to it
We can release the tool

fix: fix CI

---

common/math.go

When calculating the complement of two slices, previously we would print `Removing <ELEMENT> from slice`. The term 'slice' is go specific, and wont make sense to general users of the tool. Let's remove the reference to language-specific features, and focus on what's actually happening to the element.
This is just a logging change. CI passing should be sufficient

fix: make complement log less go-specific

---

.github/workflows/ci.yaml

Enforces conventional commit spec on all PRs
Branch off of this branch, add a non-conventional commit to the tree, push it, and run the action.
Users are forced to use conventional commits, meaning releases can be correctly versioned
I've inspected the critical paths for us, and couldn't see anything obviously sneaky going on. Pinning to a particular commit hash will stop the code changing under our feet.
opensource-nepal is quite a small org, and seems to be entirely dependent on volunteers, so it's possible this could go unmainainted for a while. I'm not super concerned about the security implications of this, for the following reasons:
- It's a pretty small app with [relatively few dependencies](https://github.com/opensource-nepal/commitlint/blob/02e7ff4f7f1e4b1f8e2955b114bfa9271f1c7c97 …

Introduce commit linting

---

README.md
script/dash-lint.sh

- Tests for additional, common mistakes in spelling fsbp-fix
- Removes the requirement for exclusions in particular areas of the code, as we are no longer required to pass in the full bad string, just the delimiter we want to check for
- CI should still pass.
- If you want to check the unhappy path, just type `fsbpfix` somewhere in the readme and run `./script/dash-lint.sh fsbp-fix`

Check for a couple more erroneous delimiters at CI time

---

README.md

Earlier in this readme, we explain what [S3.8 is evaluating](https://github.com/guardian/fsbp-tools/blob/278cbaf605ac7ade92c777833a6b01fd62679d01/README.md?plain=1#L14). For consistency, and to save a few google searches, I've added a similar line to the EC2.2 section of the README
No testing required.
Users don't need to look up EC2.2 in the Security Hub documentation

docs: Explain what EC2.2 is evaluating

---

.releaserc.json

We are merging monthly version updates (and additional ones when security advisories are released), but not releasing new versions of the tool unless a human fixes a bug/adds a feature. This defeats the point of timely security updates. This change creates a patch release when a dependency update is merged, which can then be propagated to homebrew
More frequent releases - better security for end users

trigger a patch release when dependencies are updated

---

bucket-utils/bucketblocker.go
common/aws.go
main.go
vpc-utils/ingressinquisition.go

AWS already has a function called `GetDefaultConfig`. I've renamed our implementation `Auth`, to avoid confusion, and we are now using it in a consistent way, only authenticating once per run. One of the params passed to `Auth` is region, and when we add multi-region support for this tool, it will make it easier to ensure that we are not switching regions by accident by reauthenticating partway through an operation (which was happening in `GetAccountId`).
Run the tool locally to verify auth is working
Easier to read code, fewer auth calls to aws

Rename LoadDefaultConfig, and reuse it

---

common/io.go
vpc-utils/ingressinquisition.go

SecurityHub can only be deployed into accounts that are enabled by the delegated administrator. If a member account has enabled additional opt-in regions, the tool will fail as it won't be able to detect a Hub in that region, and we will not be able to delete any group rules. This change turns that error into a warning, so we can still run in other regions
I've run the tool in one of the accounts that has this edge case, and we are no longer seeing failures

if one region fails, continue with the others
